#!/usr/bin/csh
set folder = loss_init

if (! -d ./$folder) then
	mkdir ./$folder
endif
set case_dir = "./$folder"
foreach length (20 40 80 160)
	foreach loss (0.04 0.05 0.06 0.07 0.08 0.09)
		if (-e result.txt) then
			rm -f result.txt
		endif
		@ cnt = 0
		while ($cnt < 100)
			# the syntax of python file: run_BB84_loss.py length loss_init loss_length
			# set loss_length = 0.05
			python3 run_BB84_loss.py $length $loss 0.05
			@ cnt++
		end
		mv -f result.txt $case_dir/length_{$length}_loss_{$loss}.txt
	end
end
#EOF
