#!/usr/bin/csh
set folder = loss_length
if (! -d ./$folder) then
	mkdir ./$folder
endif
set case_dir = "./$folder"
foreach length (20 40 80 160)
	set f_result = "length_{$length}.txt"
	if (-e $f_result) then
		rm -f $f_result
	endif
	foreach loss (0.04 0.05 0.06 0.07 0.08 0.09)
		if (-e result.txt) then
			rm -f result.txt
		endif
		@ cnt = 0
		while ($cnt < 100)
			# the syntax of python file: run_BB84_loss.py length loss_init loss_length
			# set loss_init = 0.05
			python3 run_BB84_loss.py $length 0.05 $loss
			@ cnt++
		end
		set result = `python3 agg.py result.txt`
		echo "$loss $result" >> $f_result
		mv -f result.txt $case_dir/length_{$length}_loss_{$loss}.txt
	end
	mv -f $f_result $case_dir
end
#EOF
